# Generated by Django 4.2.1 on 2023-05-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_image_alter_application_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sender_name',
            field=models.CharField(max_length=20, verbose_name='Имя заказчика'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.work', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
