# Generated by Django 4.2.1 on 2023-05-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_application_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.CharField(max_length=16, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='telephone_number',
            name='number',
            field=models.CharField(help_text='В формате +7(000)000-00-00', max_length=16, verbose_name='Номер для связи'),
        ),
    ]
